using System.Collections.ObjectModel;
using HealthFit.Model;

namespace HealthFit.ViewModel
{
    public class FoodListPageViewModel
    {
        public ObservableCollection<FoodList> FoodsList { get; set; }
        public FoodListPageViewModel()
        {
            //new FoodList() { FoodName = "", FoodDetails = "Calorii: kcal, Proteine: g, Lipide: g, Carbohidrati: g | (100g)"}
            FoodsList = new ObservableCollection<FoodList>()
            {
                new FoodList() { FoodName = "Ardei gras roșu", FoodDetails = "Calorii: 31 kcal, Proteine: 1 g, Lipide: 0 g, Carbohidrati: 6 g | (100g)"},
                new FoodList() { FoodName = "Ardei gras galben", FoodDetails = "Calorii: 27 kcal, Proteine: 1 g, Lipide: 0.2 g, Carbohidrati: 6.2 g | (100g)"},
                new FoodList() { FoodName = "Ardei verde", FoodDetails = "Calorii: 24 kcal, Proteine: 1.4 g, Lipide: 0 g, Carbohidrati: 4 g | (100g)"},
                new FoodList() { FoodName = "Ardei capia", FoodDetails = "Calorii: 26 kcal, Proteine: 1 g, Lipide: 0.3 g, Carbohidrati: 6 g | (100g)"},
                new FoodList() { FoodName = "Ardei iute galben", FoodDetails = "Calorii: 10 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 2 g | (100g)"},
                new FoodList() { FoodName = "Ardei iute rosu", FoodDetails = "Calorii: 40 kcal, Proteine: 2 g, Lipide: 0 g, Carbohidrati: 9 g | (100g)"},
                new FoodList() { FoodName = "Ardei iute verde", FoodDetails = "Calorii: 29 kcal, Proteine: 2.5 g, Lipide: 0.6 g, Carbohidrati: 3.7 g | (100g)"},
                new FoodList() { FoodName = "Ardei (iute, congelat)", FoodDetails = "Calorii: 40 kcal, Proteine: 2.1 g, Lipide: 0.2 g, Carbohidrati: 9.5 g | (100g)"},
                new FoodList() { FoodName = "Ardei (rosu, congelat)", FoodDetails = "Calorii: 30 kcal, Proteine: 1.4 g, Lipide: 0.2 g, Carbohidrati: 5.4 g | (100g)"},
                new FoodList() { FoodName = "Ardei (verde, congelat)", FoodDetails = "Calorii: 24 kcal, Proteine: 1.4 g, Lipide: 0.1 g, Carbohidrati: 4.2 g | (100g)"},
                new FoodList() { FoodName = "Ardei (galben, congelat)", FoodDetails = "Calorii: 25 kcal, Proteine: 1.4 g, Lipide: 0.1 g, Carbohidrati: 4.7 g | (100g)"},
                new FoodList() { FoodName = "Ardei rosu fiert", FoodDetails = "Calorii: 28 kcal, Proteine: 0.9 g, Lipide: 0.2 g, Carbohidrati: 6.7 g | (100g)"},
                new FoodList() { FoodName = "Ardei verde fiert", FoodDetails = "Calorii: 26 kcal, Proteine: 0.9 g, Lipide: 0.2 g, Carbohidrati: 6.1 g | (100g)"},
                new FoodList() { FoodName = "Cartof copt", FoodDetails = "Calorii: 93 kcal, Proteine: 2.5 g, Lipide: 0.1 g, Carbohidrati: 21.2 g | (100g)"},
                new FoodList() { FoodName = "Cartofi congelați", FoodDetails = "Calorii: 90 kcal, Proteine: 1.9 g, Lipide: 0.1 g, Carbohidrati: 19.7 g | (100g)"},
                new FoodList() { FoodName = "Cartofi dulci", FoodDetails = "Calorii: 86 kcal, Proteine: 1.6 g, Lipide: 0.1 g, Carbohidrati: 20.1 g | (100g)"},
                new FoodList() { FoodName = "Cartofi dulci fierți", FoodDetails = "Calorii: 76 kcal, Proteine: 1 g, Lipide: 0 g, Carbohidrati: 18 g | (100g)"},
                new FoodList() { FoodName = "Cartofi fierți", FoodDetails = "Calorii: 87 kcal, Proteine: 1.9 g, Lipide: 0.1 g, Carbohidrati: 20.1 g | (100g)"},
                new FoodList() { FoodName = "Cartof", FoodDetails = "Calorii: 88 kcal, Proteine: 2 g, Lipide: 0.2 g, Carbohidrati: 19 g | (100g)"},
                new FoodList() { FoodName = "Castraveți", FoodDetails = "Calorii: 12 kcal, Proteine: 0.6 g, Lipide: 0.2 g, Carbohidrati: 2.2 g | (100g)"},
                new FoodList() { FoodName = "Castraveti murați", FoodDetails = "Calorii: 12 kcal, Proteine: 1 g, Lipide: 0.2 g, Carbohidrati: 3 g | (100g)"},
                new FoodList() { FoodName = "Ceapă", FoodDetails = "Calorii: 42 kcal, Proteine: 0.9 g, Lipide: 0.1 g, Carbohidrati: 10.1 g | (100g)"},
                new FoodList() { FoodName = "Ceapă nouă", FoodDetails = "Calorii: 37 kcal, Proteine:  2.2 g, Lipide: 0.3 g, Carbohidrati: 6.3 g | (100g)"},
                new FoodList() { FoodName = "Ceapă roșie", FoodDetails = "Calorii: 39 kcal, Proteine: 1.2 g, Lipide: 0.1 g, Carbohidrati: 8.3 g | (100g)"},
                new FoodList() { FoodName = "Ceapă verde", FoodDetails = "Calorii: 32 kcal, Proteine: 1.8 g, Lipide: 0.2 g, Carbohidrati: 7.3 g | (100g)"},
                new FoodList() { FoodName = "Ciuperci", FoodDetails = "Calorii: 35 kcal, Proteine: 5 g, Lipide: 0.5 g, Carbohidrati: 2.3 g | (100g)"},
                new FoodList() { FoodName = "Conopidă", FoodDetails = "Calorii: 25 kcal, Proteine: 2.4 g, Lipide: 0.1 g, Carbohidrati: 5.3 g | (100g)"},
                new FoodList() { FoodName = "Conopidă fiartă", FoodDetails = "Calorii: 23 kcal, Proteine: 1.8 g, Lipide: 0.5 g, Carbohidrati: 4.1 g | (100g)"},
                new FoodList() { FoodName = "Conopidă murată", FoodDetails = "Calorii: 25 kcal, Proteine: 2.4 g, Lipide: 0.5 g, Carbohidrati: 3.5 g | (100g)"},
                new FoodList() { FoodName = "Dovleac copt", FoodDetails = "Calorii: 20 kcal, Proteine: 1 g, Lipide: 0 g, Carbohidrati: 5 g | (100g)"},
                new FoodList() { FoodName = "Dovleac crud", FoodDetails = "Calorii: 26 kcal, Proteine: 1.1 g, Lipide: 0 g, Carbohidrati: 6.5 g | (100g)"},
                new FoodList() { FoodName = "Dovlecei", FoodDetails = "Calorii: 12 kcal, Proteine: 1 g, Lipide: 0.1 g, Carbohidrati: 2 g | (100g)"},
                new FoodList() { FoodName = "Dovlecei fierți", FoodDetails = "Calorii: 16 kcal, Proteine: 0.6 g, Lipide: 0.1 g, Carbohidrati: 3.9 g | (100g)"},
                new FoodList() { FoodName = "Fasole (congelată)", FoodDetails = "Calorii: 67 kcal, Proteine: 10.8 g, Lipide: 0.4 g, Carbohidrati: 29 g | (100g)"},
                new FoodList() { FoodName = "Fasole (uscată)", FoodDetails = "Calorii: 303 kcal, Proteine: 22.3 g, Lipide: 1.7 g, Carbohidrati: 47.7 g | (100g)"},
                new FoodList() { FoodName = "Fasole boabe fiartă", FoodDetails = "Calorii: 132 kcal, Proteine: 8.9 g, Lipide: 0.5 g, Carbohidrati: 23.7 g | (100g)"},
                new FoodList() { FoodName = "Fasole galbenă fiartă", FoodDetails = "Calorii: 35 kcal, Proteine: 1.9 g, Lipide: 0.3 g, Carbohidrati: 7.9 g | (100g)"},
                new FoodList() { FoodName = "Fasole verde", FoodDetails = "Calorii: 31 kcal, Proteine: 1.8 g, Lipide: 0.1 g, Carbohidrati: 7.1 g | (100g)"},
                new FoodList() { FoodName = "Fasole verde (conservă)", FoodDetails = "Calorii: 20 kcal, Proteine: 1.2 g, Lipide: 0.1 g, Carbohidrati: 4.5 g | (100g)"},
                new FoodList() { FoodName = "Mazare fiartă", FoodDetails = "Calorii: 84 kcal, Proteine: 5.4 g, Lipide: 0.2 g, Carbohidrati: 15.6 g | (100g)"},
                new FoodList() { FoodName = "Mazare verde", FoodDetails = "Calorii: 42 kcal, Proteine: 2.8 g, Lipide: 0.4 g, Carbohidrati: 7.6 g | (100g)"},
                new FoodList() { FoodName = "Mazare verde (conservă)", FoodDetails = "Calorii: 69 kcal, Proteine: 4.2 g, Lipide: 0.2 g, Carbohidrati: 12.6 g | (100g)"},
                new FoodList() { FoodName = "Mazare verde fragedă congelată", FoodDetails = "Calorii: 78 kcal, Proteine: 5.2 g, Lipide: 0.3 g, Carbohidrati: 14.3 g | (100g)"},
                new FoodList() { FoodName = "Morcov fiert", FoodDetails = "Calorii: 35 kcal, Proteine: 0.8 g, Lipide: 0.2 g, Carbohidrati: 8.2 g | (100g)"},
                new FoodList() { FoodName = "Morcovi", FoodDetails = "Calorii: 41 kcal, Proteine: 0.9 g, Lipide: 0.2 g, Carbohidrati: 9.6 g | (100g)"},
                new FoodList() { FoodName = "Morcovi fierti (congelati)", FoodDetails = "Calorii: 35 kcal, Proteine: 0.8 g, Lipide: 0.2 g, Carbohidrati: 8 g | (100g)"},
                new FoodList() { FoodName = "Pastarnac fiert", FoodDetails = "Calorii: 71 kcal, Proteine: 1.3 g, Lipide: 0.3 g, Carbohidrati: 17 g | (100g)"},
                new FoodList() { FoodName = "Pastarnac radacina", FoodDetails = "Calorii: 72 kcal, Proteine: 1.4 g, Lipide: 0.5 g, Carbohidrati: 15 g | (100g)"},
                new FoodList() { FoodName = "Praz", FoodDetails = "Calorii: 61 kcal, Proteine: 1.5 g, Lipide: 0.3 g, Carbohidrati: 14.2 g | (100g)"},
                new FoodList() { FoodName = "Praz (congelat)", FoodDetails = "Calorii: 31 kcal, Proteine: 0.8 g, Lipide: 0.2 g, Carbohidrati: 6.4 g | (100g)"},
                new FoodList() { FoodName = "Radacina de patrunjel", FoodDetails = "Calorii: 29 kcal, Proteine: 2.2 g, Lipide: 0.1 g, Carbohidrati: 6.5 g | (100g)"},
                new FoodList() { FoodName = "Ridiche", FoodDetails = "Calorii: 16 kcal, Proteine: 0.7 g, Lipide: 0.1 g, Carbohidrati: 3.4 g | (100g)"},
                new FoodList() { FoodName = "Ridiche neagra", FoodDetails = "Calorii: 20 kcal, Proteine: 0.7 g, Lipide: 0.1 g, Carbohidrati: 5.1 g | (100g)"},
                new FoodList() { FoodName = "Ridiche orientala", FoodDetails = "Calorii: 18 kcal, Proteine: 0.6 g, Lipide: 0.1 g, Carbohidrati: 4.1 g | (100g)"},
                new FoodList() { FoodName = "Rosii", FoodDetails = "Calorii: 18 kcal, Proteine: 0.9 g, Lipide: 0.2 g, Carbohidrati: 3.9 g | (100g)"},
                new FoodList() { FoodName = "Rosii (congelate)", FoodDetails = "Calorii: 32 kcal, Proteine: 1.6 g, Lipide: 0.3 g, Carbohidrati: 7.3 g | (100g)"},
                new FoodList() { FoodName = "Rosii cherry", FoodDetails = "Calorii: 20 kcal, Proteine: 1.3 g, Lipide: 0 g, Carbohidrati: 4 g | (100g)"},
                new FoodList() { FoodName = "Rosii uscate", FoodDetails = "Calorii: 258 kcal, Proteine: 14.1 g, Lipide: 3 g, Carbohidrati: 55.8 g | (100g)"},
                new FoodList() { FoodName = "Salata verde", FoodDetails = "Calorii: 17 kcal, Proteine: 1.2 g, Lipide: 0.3 g, Carbohidrati: 3.3 g | (100g)"},
                new FoodList() { FoodName = "Sfecla rosie cruda", FoodDetails = "Calorii: 43 kcal, Proteine: 1.6 g, Lipide: 0.1 g, Carbohidrati: 9.6 g | (100g)"},
                new FoodList() { FoodName = "Sfecla rosie fiarta", FoodDetails = "Calorii: 37 kcal, Proteine: 1.4 g, Lipide: 0.2 g, Carbohidrati: 8.5 g | (100g)"},
                new FoodList() { FoodName = "Spanac", FoodDetails = "Calorii: 23 kcal, Proteine: 2.9 g, Lipide: 0.4 g, Carbohidrati: 3.6 g | (100g)"},
                new FoodList() { FoodName = "Spanac fiert (congelat)", FoodDetails = "Calorii: 25 kcal, Proteine: 2 g, Lipide: 0 g, Carbohidrati: 3 g | (100g)"},
                new FoodList() { FoodName = "Sparanghel", FoodDetails = "Calorii: 20 kcal, Proteine: 2.2 g, Lipide: 0.1 g, Carbohidrati: 3.9 g | (100g)"},
                new FoodList() { FoodName = "Stevie cruda", FoodDetails = "Calorii: 22 kcal, Proteine: 2 g, Lipide: 0.7 g, Carbohidrati: 3.2 g | (100g)"},
                new FoodList() { FoodName = "Stevie fiarta", FoodDetails = "Calorii: 20 kcal, Proteine: 1.8 g, Lipide: 0.6 g, Carbohidrati: 2.9 g | (100g)"},
                new FoodList() { FoodName = "Telina fiarta", FoodDetails = "Calorii: 18 kcal, Proteine: 0.8 g, Lipide: 0.2 g, Carbohidrati: 4 g | (100g)"},
                new FoodList() { FoodName = "Tulpina de telina", FoodDetails = "Calorii: 14 kcal, Proteine: 0.7 g, Lipide: 0.2 g, Carbohidrati: 3.4 g | (100g)"},
                new FoodList() { FoodName = "Urzici", FoodDetails = "Calorii: 66 kcal, Proteine: 7.9 g, Lipide: 0.7 g, Carbohidrati: 7.1 g | (100g)"},
                new FoodList() { FoodName = "Usturoi verde", FoodDetails = "Calorii:  40 kcal, Proteine: 2 g, Lipide: 0 g, Carbohidrati: 8 g | (100g)"},
                new FoodList() { FoodName = "Varza", FoodDetails = "Calorii: 31 kcal, Proteine: 1.6 g, Lipide: 0.2 g, Carbohidrati: 5.7 g | (100g)"},
                new FoodList() { FoodName = "Varza (rosie)", FoodDetails = "Calorii: 32 kcal, Proteine: 1.7 g, Lipide: 0.2 g, Carbohidrati: 5.7 g | (100g)"},
                new FoodList() { FoodName = "Varza acra murata", FoodDetails = "Calorii: 20 kcal, Proteine: 1.1 g, Lipide: 0.2 g, Carbohidrati: 3.4 g | (100g)"},
                new FoodList() { FoodName = "Varza creață", FoodDetails = "Calorii: 24 kcal, Proteine: 1.4 g, Lipide: 0.1 g, Carbohidrati: 5.6 g | (100g)"},
                new FoodList() { FoodName = "Varza fiarta", FoodDetails = "Calorii: 22 kcal, Proteine: 1 g, Lipide: 0.4 g, Carbohidrati: 4.5 g | (100g)"},

                new FoodList() { FoodName = "Afine", FoodDetails = "Calorii: 57 kcal, Proteine: 0.7 g, Lipide: 0.3 g, Carbohidrati: 14.5 g | (100g)"},
                new FoodList() { FoodName = "Agrise", FoodDetails = "Calorii: 44 kcal, Proteine: 0.9 g, Lipide: 0.6 g, Carbohidrati: 10.2 g | (100g)"},
                new FoodList() { FoodName = "Ananas", FoodDetails = "Calorii: 48 kcal, Proteine: 0.4 g, Lipide: 0 g, Carbohidrati: 12 g | (100g)"},
                new FoodList() { FoodName = "Avocado", FoodDetails = "Calorii: 167 kcal, Proteine: 2 g, Lipide: 15.4 g, Carbohidrati: 8.6 g | (100g)"},
                new FoodList() { FoodName = "Banane", FoodDetails = "Calorii: 89 kcal, Proteine: 1.1 g, Lipide: 0.3 g, Carbohidrati: 22.8 g | (100g)"},
                new FoodList() { FoodName = "Banane deshidratate", FoodDetails = "Calorii: 519 kcal, Proteine: 2.3 g, Lipide: 33.6 g, Carbohidrati: 58.4 g | (100g)"},
                new FoodList() { FoodName = "Caise", FoodDetails = "Calorii: 48 kcal, Proteine: 1.4 g, Lipide: 0.4 g, Carbohidrati: 11.1 g | (100g)"},
                new FoodList() { FoodName = "Caise deshidratate", FoodDetails = "Calorii: 213 kcal, Proteine: 2.3 g, Lipide: 0.3 g, Carbohidrati: 47.3 g | (100g)"},
                new FoodList() { FoodName = "Caise uscate", FoodDetails = "Calorii: 241 kcal, Proteine: 3.4 g, Lipide: 0.5 g, Carbohidrati: 62.6 g | (100g)"},
                new FoodList() { FoodName = "Capsuni", FoodDetails = "Calorii: 32 kcal, Proteine: 0.9 g, Lipide: 0.3 g, Carbohidrati: 7.7 g | (100g)"},
                new FoodList() { FoodName = "Capsuni congelate", FoodDetails = "Calorii: 35 kcal, Proteine: 0.4 g, Lipide: 0.1 g, Carbohidrati: 9.1 g | (100g)"},
                new FoodList() { FoodName = "Catina", FoodDetails = "Calorii: 52 kcal, Proteine: 0.9 g, Lipide: 2.5 g, Carbohidrati: 10.2 g | (100g)"},
                new FoodList() { FoodName = "Cirese", FoodDetails = "Calorii: 63 kcal, Proteine: 1.1 g, Lipide: 0.2 g, Carbohidrati: 16 g | (100g)"},
                new FoodList() { FoodName = "Clementine", FoodDetails = "Calorii: 47 kcal, Proteine: 0.8 g, Lipide: 0.2 g, Carbohidrati: 12 g | (100g)"},
                new FoodList() { FoodName = "Coacaze negre", FoodDetails = "Calorii: 57 kcal, Proteine: 0.7 g, Lipide: 0.3 g, Carbohidrati: 14.5 g | (100g)"},
                new FoodList() { FoodName = "Coacaze negre (congelate)", FoodDetails = "Calorii: 50 kcal, Proteine: 0.4 g, Lipide: 0.7 g, Carbohidrati: 12.1 g | (100g)"},
                new FoodList() { FoodName = "Coacaze rosii", FoodDetails = "Calorii: 34 kcal, Proteine: 0.6 g, Lipide: 0 g, Carbohidrati: 7 g | (100g)"},
                new FoodList() { FoodName = "Coacaze rosii (congelate)", FoodDetails = "Calorii: 33 kcal, Proteine: 1.2 g, Lipide: 0 g, Carbohidrati: 5.3 g | (100g)"},
                new FoodList() { FoodName = "Coarne de padure", FoodDetails = "Calorii: 76 kcal, Proteine: 0.7 g, Lipide: 0.4 g, Carbohidrati: 16.9 g | (100g)"},
                new FoodList() { FoodName = "Corcoduse", FoodDetails = "Calorii: 27 kcal, Proteine: 0.2 g, Lipide: 0 g, Carbohidrati: 6.4 g | (100g)"},
                new FoodList() { FoodName = "Curmale (presate)", FoodDetails = "Calorii: 286 kcal, Proteine: 2.4 g, Lipide: 0 g, Carbohidrati: 73.8 g | (100g)"},
                new FoodList() { FoodName = "Curmale proaspete", FoodDetails = "Calorii: 282 kcal, Proteine: 2.5 g, Lipide: 0.4 g, Carbohidrati: 75 g | (100g)"},
                new FoodList() { FoodName = "Curmale uscate conflate", FoodDetails = "Calorii: 286 kcal, Proteine: 2.4 g, Lipide: 0 g, Carbohidrati: 73.8 g | (100g)"},
                new FoodList() { FoodName = "Dude (Agude)", FoodDetails = "Calorii: 43 kcal, Proteine: 1.4 g, Lipide: 0.4 g, Carbohidrati: 9.8 g | (100g)"},
                new FoodList() { FoodName = "Fragi", FoodDetails = "Calorii: 32 kcal, Proteine: 0.9 g, Lipide: 0.3 g, Carbohidrati: 7.2 g | (100g)"},
                new FoodList() { FoodName = "Fructul pasiunii", FoodDetails = "Calorii: 97 kcal, Proteine: 2.2 g, Lipide: 0.7 g, Carbohidrati: 23 g | (100g)"},
                new FoodList() { FoodName = "Grapefruit", FoodDetails = "Calorii: 33 kcal, Proteine: 0.6 g, Lipide: 0.1 g, Carbohidrati: 8.1 g | (100g)"},
                new FoodList() { FoodName = "Gutui", FoodDetails = "Calorii: 57 kcal, Proteine: 0.4 g, Lipide: 0.1 g, Carbohidrati: 15 g | (100g)"},
                new FoodList() { FoodName = "Kiwi", FoodDetails = "Calorii: 61 kcal, Proteine: 1 g, Lipide: 1 g, Carbohidrati: 15 g | (100g)"},
                new FoodList() { FoodName = "Lamaie", FoodDetails = "Calorii: 29 kcal, Proteine: 1.1 g, Lipide: 0.3 g, Carbohidrati: 9.3 g | (100g)"},
                new FoodList() { FoodName = "Mandarine", FoodDetails = "Calorii: 53 kcal, Proteine: 0.8 g, Lipide: 0.3 g, Carbohidrati: 13.3 g | (100g)"},
                new FoodList() { FoodName = "Mango", FoodDetails = "Calorii: 65 kcal, Proteine: 0.5 g, Lipide: 0.3 g, Carbohidrati: 17 g | (100g)"},
                new FoodList() { FoodName = "Mango deshidratat", FoodDetails = "Calorii: 331 kcal, Proteine: 0.7 g, Lipide: 0.8 g, Carbohidrati: 83.1 g | (100g)"},
                new FoodList() { FoodName = "Mar confiat", FoodDetails = "Calorii: 242 kcal, Proteine: 0.9 g, Lipide: 0.3 g, Carbohidrati: 65.9 g | (100g)"},
                new FoodList() { FoodName = "Mar golden", FoodDetails = "Calorii: 49 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 11.2 g | (100g)"},
                new FoodList() { FoodName = "Mar ionatan", FoodDetails = "Calorii: 52 kcal, Proteine: 0.4 g, Lipide: 0.2 g, Carbohidrati: 13.8 g | (100g)"},
                new FoodList() { FoodName = "Mar verde", FoodDetails = "Calorii: 51 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 12.7 g | (100g)"},
                new FoodList() { FoodName = "Masline kalamon", FoodDetails = "Calorii: 300 kcal, Proteine: 0 g, Lipide: 26.7 g, Carbohidrati: 13.3 g | (100g)"},
                new FoodList() { FoodName = "Masline mamut", FoodDetails = "Calorii: 150 kcal, Proteine: 0 g, Lipide: 13 g, Carbohidrati: 10 g | (100g)"},
                new FoodList() { FoodName = "Masline negre", FoodDetails = "Calorii: 115 kcal, Proteine: 0.8 g, Lipide: 10.7 g, Carbohidrati: 6.3 g | (100g)"},
                new FoodList() { FoodName = "Masline verzi", FoodDetails = "Calorii: 145 kcal, Proteine: 1 g, Lipide: 15.3 g, Carbohidrati: 3.8 g | (100g)"},
                new FoodList() { FoodName = "Mure", FoodDetails = "Calorii: 43 kcal, Proteine: 1.4 g, Lipide: 0.5 g, Carbohidrati: 9.6 g | (100g)"},
                new FoodList() { FoodName = "Mure (congelate)", FoodDetails = "Calorii: 37 kcal, Proteine: 1.6 g, Lipide: 0 g, Carbohidrati: 6.4 g | (100g)"},
                new FoodList() { FoodName = "Nectarine", FoodDetails = "Calorii: 47 kcal, Proteine: 0.4 g, Lipide: 0 g, Carbohidrati: 11.4 g | (100g)"},
                new FoodList() { FoodName = "Papaya", FoodDetails = "Calorii: 39 kcal, Proteine: 0.6 g, Lipide: 0 g, Carbohidrati: 9.8 g | (100g)"},
                new FoodList() { FoodName = "Papaya confiata", FoodDetails = "Calorii: 250 kcal, Proteine: 5 g, Lipide: 0 g, Carbohidrati: 65 g | (100g)"},
                new FoodList() { FoodName = "Pepene galben", FoodDetails = "Calorii: 34 kcal, Proteine: 0.8 g, Lipide: 0.2 g, Carbohidrati: 8.2 g | (100g)"},
                new FoodList() { FoodName = "Pepene verde", FoodDetails = "Calorii: 30 kcal, Proteine: 0.6 g, Lipide: 0.2 g, Carbohidrati: 7.6 g | (100g)"},
                new FoodList() { FoodName = "Pere", FoodDetails = "Calorii: 58 kcal, Proteine: 0.4 g, Lipide: 0.1 g, Carbohidrati: 15.5 g | (100g)"},
                new FoodList() { FoodName = "Piersici", FoodDetails = "Calorii: 39 kcal, Proteine: 0.9 g, Lipide: 0.3 g, Carbohidrati: 9.5 g | (100g)"},
                new FoodList() { FoodName = "Pomelo", FoodDetails = "Calorii: 38 kcal, Proteine: 0.8 g, Lipide: 0 g, Carbohidrati: 9.6 g | (100g)"},
                new FoodList() { FoodName = "Portocale", FoodDetails = "Calorii: 47 kcal, Proteine: 0.9 g, Lipide: 0.1 g, Carbohidrati: 11.8 g | (100g)"},
                new FoodList() { FoodName = "Prune", FoodDetails = "Calorii: 59.7 kcal, Proteine: 0.7 g, Lipide: 0 g, Carbohidrati: 13.1 g | (100g)"},
                new FoodList() { FoodName = "Prune rosii", FoodDetails = "Calorii: 47 kcal, Proteine: 0.8 g, Lipide: 0 g, Carbohidrati: 11.4 g | (100g)"},
                new FoodList() { FoodName = "Prune uscate", FoodDetails = "Calorii: 240 kcal, Proteine: 2.2 g, Lipide: 0.4 g, Carbohidrati: 63.9 g | (100g)"},
                new FoodList() { FoodName = "Rodii", FoodDetails = "Calorii: 83 kcal, Proteine: 1.7 g, Lipide: 1.2 g, Carbohidrati: 18.7 g | (100g)"},
                new FoodList() { FoodName = "Smochine proaspete", FoodDetails = "Calorii: 74 kcal, Proteine: 0.8 g, Lipide: 0.3 g, Carbohidrati: 19.2 g | (100g)"},
                new FoodList() { FoodName = "Smochine uscate", FoodDetails = "Calorii: 249 kcal, Proteine: 3.3 g, Lipide: 0.9 g, Carbohidrati: 63.9 g | (100g)"},
                new FoodList() { FoodName = "Stafide", FoodDetails = "Calorii: 299 kcal, Proteine: 3.1 g, Lipide: 0.5 g, Carbohidrati: 79.2 g | (100g)"},
                new FoodList() { FoodName = "Struguri", FoodDetails = "Calorii: 69 kcal, Proteine: 0.7 g, Lipide: 0.2 g, Carbohidrati: 18.1 g | (100g)"},
                new FoodList() { FoodName = "Visine", FoodDetails = "Calorii: 50 kcal, Proteine: 1 g, Lipide: 0.3 g, Carbohidrati: 12.2 g | (100g)"},
                new FoodList() { FoodName = "Visine (congelate)", FoodDetails = "Calorii: 48 kcal, Proteine: 0.5 g, Lipide: 0 g, Carbohidrati: 10.8 g | (100g)"},
                new FoodList() { FoodName = "Zarzare", FoodDetails = "Calorii: 46 kcal, Proteine: 0.7 g, Lipide: 0.3 g, Carbohidrati: 11.4 g | (100g)"},
                new FoodList() { FoodName = "Zmeura", FoodDetails = "Calorii: 52 kcal, Proteine: 1.2 g, Lipide: 0.7 g, Carbohidrati: 11.9 g | (100g)"},
                new FoodList() { FoodName = "Zmeura (congelata)", FoodDetails = "Calorii: 45.2 kcal, Proteine: 1.1 g, Lipide: 0 g, Carbohidrati: 10.2 g | (100g)"},

                new FoodList() { FoodName = "Alune", FoodDetails = "Calorii: 567 kcal, Proteine: 26 g, Lipide: 49 g, Carbohidrati: 16 g | (100g)"},
                new FoodList() { FoodName = "Arahide", FoodDetails = "Calorii: 628 kcal, Proteine: 22 g, Lipide: 52.4 g, Carbohidrati: 13.2 g | (100g)"},
                new FoodList() { FoodName = "Caju", FoodDetails = "Calorii: 553 kcal, Proteine: 18 g, Lipide: 44 g, Carbohidrati: 30 g | (100g)"},
                new FoodList() { FoodName = "Castane coapte", FoodDetails = "Calorii: 245 kcal, Proteine: 3 g, Lipide: 2 g, Carbohidrati: 53 g | (100g)"},
                new FoodList() { FoodName = "Castane crude", FoodDetails = "Calorii: 97 kcal, Proteine: 1.4 g, Lipide: 0.1 g, Carbohidrati: 23.9 g | (100g)"},
                new FoodList() { FoodName = "Castane fierte", FoodDetails = "Calorii: 211 kcal, Proteine: 4.6 g, Lipide: 2 g, Carbohidrati: 40 g | (100g)"},
                new FoodList() { FoodName = "Fistic", FoodDetails = "Calorii: 562 kcal, Proteine: 20.3 g, Lipide: 45.4 g, Carbohidrati: 27.5 g | (100g)"},
                new FoodList() { FoodName = "Mac", FoodDetails = "Calorii: 533 kcal, Proteine: 18 g, Lipide: 44.7 g, Carbohidrati: 23.9 g | (100g)"},
                new FoodList() { FoodName = "Miez de nuca", FoodDetails = "Calorii: 675 kcal, Proteine: 14.4 g, Lipide: 62.5 g, Carbohidrati: 10.6 g | (100g)"},
                new FoodList() { FoodName = "Migdale", FoodDetails = "Calorii: 578 kcal, Proteine: 21.3 g, Lipide: 50.6 g, Carbohidrati: 19.7 g | (100g)"},
                new FoodList() { FoodName = "Nuca de cocos", FoodDetails = "Calorii: 354 kcal, Proteine: 3.3 g, Lipide: 33.5 g, Carbohidrati: 15.2 g | (100g)"},
                new FoodList() { FoodName = "Nuci", FoodDetails = "Calorii: 654 kcal, Proteine: 15.2 g, Lipide: 65.2 g, Carbohidrati: 13.7 g | (100g)"},

                new FoodList() { FoodName = "Aripi de pui gatite", FoodDetails = "Calorii: 290 kcal, Proteine: 26.9 g, Lipide: 19.5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Burta vita", FoodDetails = "Calorii: 168 kcal, Proteine: 15.9 g, Lipide: 11.2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne cal", FoodDetails = "Calorii: 113 kcal, Proteine: 21.5 g, Lipide: 2.5 g, Carbohidrati: 0.9 g | (100g)"},
                new FoodList() { FoodName = "Carne capra", FoodDetails = "Calorii: 109 kcal, Proteine: 20.6 g, Lipide: 2.3 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne caprioara", FoodDetails = "Calorii: 105 kcal, Proteine: 20.8 g, Lipide: 1.9 g, Carbohidrati: 0.4 g | (100g)"},
                new FoodList() { FoodName = "Carne de berbec", FoodDetails = "Calorii: 109 kcal, Proteine: 22 g, Lipide: 2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de gasca", FoodDetails = "Calorii: 238 kcal, Proteine: 29 g, Lipide: 13 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de gasca (grasa)", FoodDetails = "Calorii: 392 kcal, Proteine: 16 g, Lipide: 35 g, Carbohidrati: 0.2 g | (100g)"},
                new FoodList() { FoodName = "Carne de porc semi-grasa", FoodDetails = "Calorii: 212 kcal, Proteine: 29.3 g, Lipide: 9.7 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de porc grasa", FoodDetails = "Calorii: 340 kcal, Proteine: 15 g, Lipide: 30 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de de rata", FoodDetails = "Calorii: 201 kcal, Proteine: 23.5 g, Lipide: 11.2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de vaca grasa", FoodDetails = "Calorii: 277 kcal, Proteine: 12 g, Lipide: 24.5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de vaca slaba", FoodDetails = "Calorii: 104 kcal, Proteine: 20.4 g, Lipide: 2.2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de vita gatita", FoodDetails = "Calorii: 188 kcal, Proteine: 30.3 g, Lipide: 6.6 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de porc muschi file crud", FoodDetails = "Calorii: 120 kcal, Proteine: 21 g, Lipide: 3.4 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Ceafa de porc", FoodDetails = "Calorii: 194 kcal, Proteine: 19.6 g, Lipide: 12.3 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Ceafa de vita", FoodDetails = "Calorii: 180 kcal, Proteine: 20 g, Lipide: 11 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de cerb", FoodDetails = "Calorii: 123 kcal, Proteine: 20.7 g, Lipide: 3.9 g, Carbohidrati: 0.6 g | (100g)"},
                new FoodList() { FoodName = "Ciolan de porc", FoodDetails = "Calorii: 337 kcal, Proteine: 16 g, Lipide: 29 g, Carbohidrati: 0.3 g | (100g)"},
                new FoodList() { FoodName = "Coasta de miel grasa", FoodDetails = "Calorii: 361 kcal, Proteine: 22.1 g, Lipide: 29.6 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Coasta de porc", FoodDetails = "Calorii: 186 kcal, Proteine: 20.3 g, Lipide: 11 g, Carbohidrati: 0.4 g | (100g)"},
                new FoodList() { FoodName = "Costita de vita", FoodDetails = "Calorii: 263 kcal, Proteine: 16 g, Lipide: 21 g, Carbohidrati: 0.5 g | (100g)"},
                new FoodList() { FoodName = "Costita de porc", FoodDetails = "Calorii: 155 kcal, Proteine: 21.6 g, Lipide: 7 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Creier porc", FoodDetails = "Calorii: 127 kcal, Proteine: 10.3 g, Lipide: 9.2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Creier vita", FoodDetails = "Calorii: 143 kcal, Proteine: 10.9 g, Lipide: 10.3 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de fazan", FoodDetails = "Calorii: 111 kcal, Proteine: 22.3 g, Lipide: 1.9 g, Carbohidrati: 0.5 g | (100g)"},
                new FoodList() { FoodName = "Carne de pui", FoodDetails = "Calorii: 140 kcal, Proteine: 19 g, Lipide: 6.5 g, Carbohidrati: 0.4 g | (100g)"},
                new FoodList() { FoodName = "Carne de iepure", FoodDetails = "Calorii: 106 kcal, Proteine: 23 g, Lipide: 1.1 , Carbohidrati: 0.5 g | (100g)"},
                new FoodList() { FoodName = "Inima de miel", FoodDetails = "Calorii: 120 kcal, Proteine: 17.1 g, Lipide: 5.6 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Inima de porc", FoodDetails = "Calorii: 148 kcal, Proteine: 24 g, Lipide: 5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Inima de pui", FoodDetails = "Calorii: 153 kcal, Proteine: 16 g, Lipide: 9 g, Carbohidrati: 1 g | (100g)"},
                new FoodList() { FoodName = "Inima de vita", FoodDetails = "Calorii: 165 kcal, Proteine: 29 g, Lipide: 5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de oaie (semi-grasa)", FoodDetails = "Calorii: 316 kcal, Proteine: 16.9 g, Lipide: 26.4 g, Carbohidrati: 0.3 g | (100g)"},
                new FoodList() { FoodName = "Piept de curcan crud", FoodDetails = "Calorii: 107 kcal, Proteine: 25 g, Lipide: 0.4 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Piept de porc cu coaste", FoodDetails = "Calorii: 241 kcal, Proteine: 12.4 g, Lipide: 17.6 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Piept de pui crud", FoodDetails = "Calorii: 172 kcal, Proteine: 20.9 g, Lipide: 9.2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de porc mistret", FoodDetails = "Calorii: 112 kcal, Proteine: 21.6 g, Lipide: 2.4 g, Carbohidrati: 0.4 g | (100g)"},
                new FoodList() { FoodName = "Carne de porumbel", FoodDetails = "Calorii: 130 kcal, Proteine: 19.6 g, Lipide: 5 g, Carbohidrati: 1.2 g | (100g)"},
                new FoodList() { FoodName = "Pulpa de curcan", FoodDetails = "Calorii: 112 kcal, Proteine: 15 g, Lipide: 5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Carne de strut", FoodDetails = "Calorii: 114 kcal, Proteine: 25.4 g, Lipide: 1.4 g, Carbohidrati: 0 g | (100g)"},

                new FoodList() { FoodName = "Albus de ou", FoodDetails = "Calorii: 52 kcal, Proteine: 10.9 g, Lipide: 0.2 g, Carbohidrati: 0.7 g | (100g)"},
                new FoodList() { FoodName = "Galbenus de ou", FoodDetails = "Calorii: 322 kcal, Proteine: 16 g, Lipide: 27 g, Carbohidrati: 3.6 g | (100g)"},
                new FoodList() { FoodName = "Ou curcă", FoodDetails = "Calorii: 171 kcal, Proteine: 13.7 g, Lipide: 11.9 g, Carbohidrati: 1.2 g | (100g)"},
                new FoodList() { FoodName = "Ou de gaina", FoodDetails = "Calorii: 155 kcal, Proteine: 13 g, Lipide: 11 g, Carbohidrati: 1.1 g | (100g)"},
                new FoodList() { FoodName = "Ou de gasca", FoodDetails = "Calorii: 185 kcal, Proteine: 13.6 g, Lipide: 15.3 g, Carbohidrati: 0.9 g | (100g)"},
                new FoodList() { FoodName = "Ou de prepelita", FoodDetails = "Calorii: 158 kcal, Proteine: 13 g, Lipide: 11 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Ou de rata", FoodDetails = "Calorii: 185 kcal, Proteine: 12.8 g, Lipide: 13.8 g, Carbohidrati: 1.5 g | (100g)"},

                new FoodList() { FoodName = "Branza daneza", FoodDetails = "Calorii: 450 kcal, Proteine: 6 g, Lipide: 19 g, Carbohidrati: 62 g | (100g)"},
                new FoodList() { FoodName = "Branza de burduf", FoodDetails = "Calorii: 369 kcal, Proteine: 27.4 g, Lipide: 27.4 g, Carbohidrati: 0.5 g | (100g)"},
                new FoodList() { FoodName = "Branza de oaie", FoodDetails = "Calorii: 283 kcal, Proteine: 18.2 g, Lipide: 21.1 g, Carbohidrati: 3 g | (100g)"},
                new FoodList() { FoodName = "Branza de vaca", FoodDetails = "Calorii: 285 kcal, Proteine: 11.5 g, Lipide: 24.9 g, Carbohidrati: 1.5 g | (100g)"},
                new FoodList() { FoodName = "Branza feta", FoodDetails = "Calorii: 264 kcal, Proteine: 14.2 g, Lipide: 21.3 g, Carbohidrati: 4.1 g | (100g)"},
                new FoodList() { FoodName = "Branza ricotta", FoodDetails = "Calorii: 138 kcal, Proteine: 11 g, Lipide: 8 g, Carbohidrati: 5 g | (100g)"},
                new FoodList() { FoodName = "Cas de oaie", FoodDetails = "Calorii: 280 kcal, Proteine: 25 g, Lipide: 19 g, Carbohidrati: 2.3 g | (100g)"},
                new FoodList() { FoodName = "Cas de vaca", FoodDetails = "Calorii: 254 kcal, Proteine: 24.3 g, Lipide: 16 g, Carbohidrati: 2.8 g | (100g)"},
                new FoodList() { FoodName = "Cascaval", FoodDetails = "Calorii: 283 kcal, Proteine: 25 g, Lipide: 19 g, Carbohidrati: 1 g | (100g)"},
                new FoodList() { FoodName = "Gorgonzola", FoodDetails = "Calorii: 350 kcal, Proteine: 21 g, Lipide: 28 g, Carbohidrati: 1.5 g | (100g)"},
                new FoodList() { FoodName = "Mozzarella", FoodDetails = "Calorii: 318 kcal, Proteine: 21.6 g, Lipide: 24.6 g, Carbohidrati: 2.5 g | (100g)"},
                new FoodList() { FoodName = "Parmezan", FoodDetails = "Calorii: 431 kcal, Proteine: 38.5 g, Lipide: 28.6 g, Carbohidrati: 4.1 g | (100g)"},
                new FoodList() { FoodName = "Smantana 12%", FoodDetails = "Calorii: 141 kcal, Proteine: 3.8 g, Lipide: 12 g, Carbohidrati: 4.5 g | (100g)"},
                new FoodList() { FoodName = "Urda", FoodDetails = "Calorii: 136 kcal, Proteine: 18 g, Lipide: 4 g, Carbohidrati: 6 g | (100g)"},

                new FoodList() { FoodName = "Covrig", FoodDetails = "Calorii: 331 kcal, Proteine: 10.5 g, Lipide: 7.1 g, Carbohidrati: 56.6 g | (100g)"},

                new FoodList() { FoodName = "Calamar", FoodDetails = "Calorii: 92 kcal, Proteine: 15.6 g, Lipide: 1.4 g, Carbohidrati: 3.1 g | (100g)"},
                new FoodList() { FoodName = "Caracatita", FoodDetails = "Calorii: 82 kcal, Proteine: 14.9 g, Lipide: 1 g, Carbohidrati: 2.2 g | (100g)"},
                new FoodList() { FoodName = "Caras", FoodDetails = "Calorii: 102 kcal, Proteine: 20.7 g, Lipide: 2.1 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Cod", FoodDetails = "Calorii: 107 kcal, Proteine: 24 g, Lipide: 1 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Crap", FoodDetails = "Calorii: 127 kcal, Proteine: 17.8 g, Lipide: 5.6 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Creveti cruzi", FoodDetails = "Calorii: 106 kcal, Proteine: 20.3 g, Lipide: 1.7 g, Carbohidrati: 0.9 g | (100g)"},
                new FoodList() { FoodName = "Icre crap", FoodDetails = "Calorii: 130 kcal, Proteine: 25 g, Lipide: 3 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Icre hering", FoodDetails = "Calorii: 91 kcal, Proteine: 16 g, Lipide: 2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Icre somon", FoodDetails = "Calorii: 245 kcal, Proteine: 32 g, Lipide: 13 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Icre stiuca", FoodDetails = "Calorii: 125 kcal, Proteine: 27 g, Lipide: 1.5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Macrou crud", FoodDetails = "Calorii: 205 kcal, Proteine: 18.6 g, Lipide: 13.9 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Pastrav crud", FoodDetails = "Calorii: 148 kcal, Proteine: 20.8 g, Lipide: 6. g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Rac", FoodDetails = "Calorii: 77 kcal, Proteine: 14.9 g, Lipide: 0.8 g, Carbohidrati: 2.2 g | (100g)"},
                new FoodList() { FoodName = "Rechin", FoodDetails = "Calorii: 130 kcal, Proteine: 21 g, Lipide: 5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Salau", FoodDetails = "Calorii: 86 kcal, Proteine: 19 g, Lipide: 0.8 g, Carbohidrati: 0.2 g | (100g)"},
                new FoodList() { FoodName = "Sardina proaspata", FoodDetails = "Calorii: 125 kcal, Proteine: 20 g, Lipide: 5 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Scoici", FoodDetails = "Calorii: 82 kcal, Proteine: 9 g, Lipide: 2 g, Carbohidrati: 6.5 g | (100g)"},
                new FoodList() { FoodName = "Sepie cruda", FoodDetails = "Calorii: 79 kcal, Proteine: 16.2 g, Lipide: 0.7 g, Carbohidrati: 0.8 g | (100g)"},
                new FoodList() { FoodName = "Somn", FoodDetails = "Calorii: 280 kcal, Proteine: 17.5 g, Lipide: 18 g, Carbohidrati: 0.2 g | (100g)"},
                new FoodList() { FoodName = "Somon", FoodDetails = "Calorii: 127 kcal, Proteine: 20.5 g, Lipide: 4.4 g, Carbohidrati: 0.2 g | (100g)"},
                new FoodList() { FoodName = "Stiuca", FoodDetails = "Calorii: 88 kcal, Proteine: 19.3 g, Lipide: 0.7 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Stridii", FoodDetails = "Calorii: 59 kcal, Proteine: 5.2 g, Lipide: 1.6 g, Carbohidrati: 5.5 g | (100g)"},
                new FoodList() { FoodName = "Sturion", FoodDetails = "Calorii: 135 kcal, Proteine: 20.7 g, Lipide: 5.2 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Tipar", FoodDetails = "Calorii: 295 kcal, Proteine: 15 g, Lipide: 25 g, Carbohidrati: 0 g | (100g)"},

                new FoodList() { FoodName = "Baclava", FoodDetails = "Calorii: 490 kcal, Proteine: 5 g, Lipide: 36 g, Carbohidrati: 36 g | (100g)"},
                new FoodList() { FoodName = "Biscuiti cu crema", FoodDetails = "Calorii: 428 kcal, Proteine: 7.2g, Lipide: 10.4g, Carbohidrati: 73.6g | (100g)"},
                new FoodList() { FoodName = "Caramele", FoodDetails = "Calorii: 382 kcal, Proteine: 4.6 g, Lipide: 8.1 g, Carbohidrati: 77 g | (100g)"},
                new FoodList() { FoodName = "Chec", FoodDetails = "Calorii: 384 kcal, Proteine: 6.4 g, Lipide: 17.6 g, Carbohidrati: 53.5 g | (100g)"},
                new FoodList() { FoodName = "Inghetata", FoodDetails = "Calorii: 164 kcal, Proteine: 2.2 g, Lipide: 4.5 g, Carbohidrati: 27.8 g | (100g)"},

                new FoodList() { FoodName = "Bere", FoodDetails = "Calorii: 43 kcal, Proteine: 0.5 g, Lipide: 0 g, Carbohidrati: 3.5 g | (100g)"},
                new FoodList() { FoodName = "Cafea", FoodDetails = "Calorii: 1 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Ceai", FoodDetails = "Calorii: 0 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 0 g | (100g)"},
                new FoodList() { FoodName = "Ciocolata calda", FoodDetails = "Calorii: 353 kcal, Proteine: 6 g, Lipide: 12 g, Carbohidrati: 59 g | (100g)"},
                new FoodList() { FoodName = "Coca-Cola", FoodDetails = "Calorii: 42 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 10.6 g | (100g)"},
                new FoodList() { FoodName = "Coca-Cola Cherry", FoodDetails = "Calorii: 45 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 11.2 g | (100g)"},
                new FoodList() { FoodName = "Coca-Cola light", FoodDetails = "Calorii: 0.5 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 0g | (100g)"},
                new FoodList() { FoodName = "Coca-Cola Zero", FoodDetails = "Calorii: 0.2 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 0g | (100g)"},
                new FoodList() { FoodName = "Fanta", FoodDetails = "Calorii: 46 kcal, Proteine: 0 g, Lipide: 0 g, Carbohidrati: 14.6 g | (100g)"},

                new FoodList() { FoodName = "Paine alba", FoodDetails = "Calorii: 266 kcal, Proteine: 7.6 g, Lipide: 3.3 g, Carbohidrati: 50.6 g | (100g)"},
                new FoodList() { FoodName = "Paine de casa", FoodDetails = "Calorii: 260 kcal, Proteine: 9.1 g, Lipide: 4.1 g, Carbohidrati: 47.2 g | (100g)"},
                new FoodList() { FoodName = "Paine de secara", FoodDetails = "Calorii: 258 kcal, Proteine: 9 g, Lipide: 3 g, Carbohidrati: 48 g | (100g)"},
                new FoodList() { FoodName = "Paine de tarate", FoodDetails = "Calorii: 194 kcal, Proteine: 9 g, Lipide: 2 g, Carbohidrati: 44 g | (100g)"},
                new FoodList() { FoodName = "Paine graham", FoodDetails = "Calorii: 268 kcal, Proteine: 10.1 g, Lipide: 1 g, Carbohidrati: 54 g | (100g)"},
                new FoodList() { FoodName = "Paine neagra", FoodDetails = "Calorii: 249 kcal, Proteine: 8.5 g, Lipide: 0.8 g, Carbohidrati: 50.6 g | (100g)"},
            };
        }
    }
}
